services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: ['npm', 'run', 'start:prod']
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis:/data

  postgres:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  postgres:
    driver: local
